spring:
  application:
    name: 46-SB_CONFIG_SERVER-App
  cloud:
    config:
      server:
        git:
          uri: https://github.com/amdevsonu/configuration_properties
          clone-on-start: true
management:
  security:
   enabled: false
